### ISSUE TITLE
Add missing BestOfJS data

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS#89]
I'm not sure why (maybe a mismatch with keys?) but some of the tooltips are not showing up: 

![https://d3vv6lp55qjaqc.cloudfront.net/items/1x2V3I0b2K1U1z3B2O2m/Screen%20Shot%202018-11-03%20at%2020.29.39.png?X-CloudApp-Visitor-Id=43642&v=b02f11fe](https://d3vv6lp55qjaqc.cloudfront.net/items/1x2V3I0b2K1U1z3B2O2m/Screen%20Shot%202018-11-03%20at%2020.29.39.png?X-CloudApp-Visitor-Id=43642&v=b02f11fe)

I think we're still relying on a `yml` file but maybe @michaelrambeau you could add a GraphQL integration to get live data like we did for the periodic table in the `/home` project?

**Comment by michaelrambeau** [comment]
The 2018 survey Gatsby app relies on a JSON file `surveys/2018/website/src/data` but it seems there is a confusion between project names ("VueX") and slugs ("vuex"), I guess `elm` data was found because the name is the same as the slug (all letters are lowercase).

Trying to run the project in local to investigate more, it would be better to fetch data at build time like we did on the `/home` project indeed...

Note: we don't have data for some projects like "MongoDB" (not tracked on _Best of JavaScript_)

**Comment by plouc** [comment]
now every tool is defined in `state-of-js/data-pipeline/conf/tools.js`, but the graphql integration should be added as a lot of tools are missing from our actual data.

**Comment by michaelrambeau** [comment]
Fixed by this PR https://github.com/StateOfJS/StateOfJS/pull/111

The previous PR was closed without merging.

**Comment by plouc** [comment]
Thank you @michaelrambeau
